import './globals.css'
import { Inter } from 'next/font/google'
import { TheHeader } from "@/app/component/header";
import { TheFooter } from "@/app/component/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <TheHeader />
      <main>
        {children}
      </main>
      <TheFooter />
      </body>
    </html>
  )
}
