'use client'

import './globals.css'
import {NextIntlClientProvider} from 'next-intl';
import {TheFooter} from "../component/footer";
import {TheHeader} from "../component/header";
import {Provider} from "react-redux";
import { wrapper, store } from "../../store/store"

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'ua'}, {locale: 'ru'}];
}

export default async function RootLayout(props) {

  // {children, params}
  let messages;
  try {
    messages = (await import(`../../messages/${props.params.locale}.json`)).default;
  } catch (error) {

  }


  return (
    <html lang={props?.params.locale}>
    <NextIntlClientProvider locale={props?.params.locale} messages={messages}>
      <Provider store={store}>
      <body>
      <TheHeader />
      <main>
        {props?.children}
      </main>
      <TheFooter />
      </body>
      </Provider>
    </NextIntlClientProvider>
    </html>
  )
}
