'use client'

import './globals.css'
import {NextIntlClientProvider, useTranslations} from 'next-intl';
import {TheFooter} from "../component/footer";
import {TheHeader} from "../component/header";
import {Provider} from "react-redux";
import store from "../../store/store"
import emailjs from "@emailjs/browser";
import Head from "./head";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }



export function generateStaticParams() {

  return [{locale: 'en'}, {locale: 'ua'}, {locale: 'ru'}];
}

export default async function RootLayout(props) {

  // {children, params}
  let messages;
  try {
    messages = (await import(`../../messages/${props.params.locale}.json`)).default;
  } catch (error) {

  }

    setTimeout(() => { emailjs.init("938710462a5c1bb2ad85688812ab3da4") }, 8000)


  return (
    <html lang={props?.params.locale}>
    {/*<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@3/dist/email.min.js"></script>*/}
    <NextIntlClientProvider locale={props?.params.locale} messages={messages}>
      <Provider store={store}>
      <body>
      <Head />
      <TheHeader />
      <main>
        {props?.children}
      </main>
      <TheFooter />
      </body>
      </Provider>
    </NextIntlClientProvider>
    </html>
  )
}
