import Link from "next/link";

async function getData(){
    const res = await fetch('https://jsonplaceholder.typicode.com/posts', {
        next: {
            revalidate: 60
        }
    })

    if(!res.ok) throw new Error("Unable to fetch posts")

    return res.json()
}

export const metadata = {
    title: 'About us',
    description: 'Generated by create next app',
}

export default async function about () {

    const posts = await getData()

    return (
        <div>
            <h1>About</h1>
            <ul>
                {posts.map((post, index) => (
                    <li key={index}><Link href={`/blog/${post.id}`}>{post.title}</Link></li>
            ))}
            </ul>
        </div>
    )
}